version: '2'
services:
  api:
    image: eregs/core
    ports:
      - 8080:8080
    environment:
      ALLOWED_HOST: api
  parser:
    image: eregs/parser
    volumes:
      - parser_data:/app/cache
    depends_on:
      - api

  site2: &SITE
    build:
      context: ..
      args:
        PYTHON3: ''
    volumes:
      - $PWD/devops/local_settings.py:/app/src/local_settings.py
    environment:
      EREGS_API_BASE: 'http://api:8080/'
    depends_on:
      - api
    ports:
      - 8000:8000
  site3:
    <<: *SITE
    build:
      context: ..
      args:
        PYTHON3: '3'


volumes:
  parser_data:
