language: python
dist: trusty      # per https://github.com/travis-ci/travis-ci/issues/5448
sudo: required    # required for docker
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/node_modules
matrix:
  include:
    - python: '2.7'
    - python: '3.4'
    - python: '3.5'
    - python: '3.6'
    - python: '2.7'
      addons:
        sauce_connect: true
      env:
        INTEGRATION_TESTS: true
    - python: '3.6'
      addons:
        sauce_connect: true
      env:
        INTEGRATION_TESTS: true
before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 6.9.2
  - nvm use 6.9.2
install:
  - pip install tox-travis
  - npm install -g grunt-cli
script:
  - ./frontendbuild.sh
  - if [ "$INTEGRATION_TESTS" = "true" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./devops/integration-tests.sh; else tox; fi
